project_name: kubecron
release:
  draft: false
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: kubecron
archives:
  - id: go
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    rlcp: true
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
